name: Build and Deploy to Azure

on:
  push:
    branches:
      - main # Or the branch you want to trigger on

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Log into Azure Container Registry
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_REGISTRY_URL }}  # ACR URL (e.g., myregistry.azurecr.io)
        username: ${{ secrets.ACR_USERNAME }}  # ACR Username (or Azure Service Principal username)
        password: ${{ secrets.ACR_PASSWORD }}  # ACR Password (or Azure Service Principal password)

    # Build and push Docker image
    # [REGISTRY_URL/][NAMESPACE/]REPOSITORY:TAG
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ACR_REGISTRY_URL }}/${{ secrets.REPOSITORY_NAME }}:${{ github.sha }} ./Tailspin.SpaceGame.Web
        docker push ${{ secrets.ACR_REGISTRY_URL }}/${{ secrets.REPOSITORY_NAME }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-20.04
    needs: build
    steps:
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.WEB_APP_NAME }}  # Azure Web App Name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Azure publish profile
        images: ${{ secrets.ACR_REGISTRY_URL }}/${{ secrets.REPOSITORY_NAME }}:${{ github.sha }}
